# Overrides for the kube-prometheus-stack chart

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: admin
  defaultDashboardsTimezone: browser

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    scrapeInterval: 15s
    evaluationInterval: 15s
    retention: 24h

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 2Gi
